# Generated by Django 2.1.15 on 2021-06-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
